image: node:19-alpine3.15

stages:
  - build
  - printing
  - test

build:
  stage: build
  script:
    - npm install
    - npm run build

ngetes-print:
  stage: printing
  script:
    - echo "Hi Guys Saya Gitlab CICD"

testing-lint:
  stage: test
  trigger: manual
  script:
    - npm install
    - npm run lint
